// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Wasm = require("./wasm.bs.js");
var Block = require("bs-platform/lib/js/block.js");

var m = Wasm.modul(/* :: */[
      Wasm.func("addTwo", /* :: */[
            Wasm.param("i1", /* I32 */0),
            /* :: */[
              Wasm.param("i2", /* I32 */0),
              /* [] */0
            ]
          ], /* :: */[
            /* I32 */0,
            /* [] */0
          ], /* [] */0, /* :: */[
            /* GetLocal */Block.__(0, ["i1"]),
            /* :: */[
              /* GetLocal */Block.__(0, ["i2"]),
              /* :: */[
                /* I32Add */0,
                /* [] */0
              ]
            ]
          ], /* true */1),
      /* [] */0
    ]);

console.log(Wasm.ToSexp[/* modul */3](m));

var match = Wasm.ToBin[/* modul */4](m);

var bin = match[1];

var instance = new (WebAssembly.Instance)(new (WebAssembly.Module)(bin));

var ex = instance.exports;

console.log(ex.addTwo(1, 2));

var size = match[0];

exports.m = m;
exports.size = size;
exports.bin = bin;
exports.instance = instance;
exports.ex = ex;
/* m Not a pure module */
