// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function bitString(num, numBits) {
  var loop = function (rest, bitsLeft) {
    if (bitsLeft <= 0) {
      return "";
    } else {
      var bit = rest & 1;
      var match = +(bit === 0);
      var str = match !== 0 ? "0" : "1";
      return loop((rest >> 1), bitsLeft - 1 | 0) + str;
    }
  };
  return loop(num, numBits);
}

function hexString($$byte) {
  var loop = function (rest) {
    var quotient = rest / 16 | 0;
    var remainder = rest - (quotient << 4) | 0;
    var switcher = remainder - 10 | 0;
    var str;
    if (switcher > 5 || switcher < 0) {
      str = Pervasives.string_of_int(remainder);
    } else {
      switch (switcher) {
        case 0 : 
            str = "a";
            break;
        case 1 : 
            str = "b";
            break;
        case 2 : 
            str = "c";
            break;
        case 3 : 
            str = "d";
            break;
        case 4 : 
            str = "e";
            break;
        case 5 : 
            str = "f";
            break;
        
      }
    }
    if (quotient) {
      return loop(quotient) + str;
    } else {
      return str;
    }
  };
  return "0x" + loop($$byte);
}

exports.bitString = bitString;
exports.hexString = hexString;
/* No side effect */
